### PR TITLE
don't hit the disk every time Settings.reset() is called

### PR DESCRIPTION
**Pull request by iomintz**
In my case my server which uses this library was running out of file descriptors while being flooded.
This commit prevents that from happening

### CODE REVIEW

**Comment by Kinnay** [comment]
Are you sure that you ran out of file descriptors because of `settings.py`? The config files are properly closed by the `with` statement so this shouldn't cause any issues. I believe that the issue is elsewhere.

I just did some testing:
```python
for i in range(10):
	b = backend.BackEndClient("switch.cfg")
	b.configure(SMM2.ACCESS_KEY, SMM2.NEX_VERSION, SMM2.CLIENT_VERSION)
	b.connect(HOST, PORT)
	b.close()
```

No file descriptors were taken up by config files (based on `lsof`), but I ended up with many sockets in the `CLOSE_WAIT` state, so NintendoClients is probably not closing the sockets properly.

**Comment by iomintz** [comment]
The problem in my case was that I was opening up the files in parallel due to inbound requests being flooded. Regardless the disk should not be accessed more than once for a file that never changes. I don't have the logs to prove it but the server was definitely unable to open any more files and it was failing at settings.cfg due to the Settings.reset() call.

**Comment by Kinnay** [comment]
Is it possible that it was just a coincidence? I mean, unix uses the same file descriptors for both sockets and files as far as I know, so it's possible that all file descriptors were taken up by sockets and `Settings.reset()` happened to be the first function that tried to get a new file descriptor once they were exhausted.

The parsing of the config files really doesn't take that long, and the file descriptor is released immediately after it has been parsed. To exhaust the file descriptors this way you would have to create more threads than the number of available file descriptors, and each thread would have to be parsing a config file at the same time. I don't think that can ever happen.

Besides, the game servers don't allow concurrent logins from my experience, so you can't use multiple BackEndClient instances at the same time anyway. This means that you have to wait for one connection to be closed before opening a new one, so you'll only ever be parsing a single config file at once anyway. You should probably keep the connection alive permanently and reuse the BackEndClient to serve requests on your server. It'll also become a lot faster that way, because right now you're repeating the whole game server login on each request.

I really think the problem is with the sockets here, not the config files.

**Comment by iomintz** [comment]
Sure yeah. The problem is with the sockets. But I still don't think a library should touch the disk more than necessary. I know of a directory index server that caches the filesystem tree on startup and keeps it updated using inotify. It's the same idea.

**Comment by iomintz** [comment]
This issue's gotten stale. I still feel like not using system resources more than necessary is a good thing here, but I will close it if you're really against it.

**Comment by Kinnay** [comment]
Sure, it usually is, but unless you can show that this has a significant performance impact on your server I'm against it. Accessing a file only takes a few microseconds, whereas connecting to the game server takes more than a second.

**Pull request closed without merging**
