### PR TITLE
add 11.0.0 user agents

### PR DESCRIPTION
**Pull request by HookedBehemoth**

### CODE REVIEW

**Comment by kinnay** [comment]
Thanks.

Did you test this against the real servers too?

**Comment by HookedBehemoth** [comment]
Not yet, no

**Comment by kinnay** [comment]
Could you do that for 11.0.0? Just make sure that you can get a dauth, aauth and id token without errors.

Your PR looks good, but since it's so easy to be banned on the Switch I don't want push code to this repo that fails on dauth or aauth for whatever reason. That's also the reason I haven't added 11.0.0 support myself yet: I didn't have time to test it against real servers yet :slightly_smiling_face:

**Comment by HookedBehemoth** [comment]
tested dauth and it works
How would I go about testing aauth?

**Comment by kinnay** [comment]
Great! Try to request a token for a digital title. See [auth_digital here](https://nintendoclients.readthedocs.io/en/latest/reference/aauth/). Or look at [one of the example scripts](https://github.com/kinnay/NintendoClients/blob/master/examples/switch/animalcrossing.py#L61-L67).

**Comment by kinnay** [comment]
Ok I tested it myself. Everything works fine.

I have big changes locally for #53 and #54 that I will push to github soon. This will also add support for 11.0.0, so I won't be merging your PR. I appreciate the help though.

**Pull request closed without merging**
