### PR TITLE
add device_cert option + better match observed request

### PR DESCRIPTION
**Pull request by mrexodia**

### CODE REVIEW

**Comment by Kinnay** [comment]
Hi, I have a few comments.

* The `Accept-Language` header depends on the system language of your Wii U. My Wii U is set to German for example, so it sends "de" in the `Accept-Language` header instead of "en".
* `Accept: */*` is added automatically by the requests module as far as I can tell.
* Adding an option to send the `X-Nintendo-Device-Cert` header is a good, but it only seems to be sent in a small number of requests by a real Wii U (`oauth20/access_token/generate` for example). Your patch includes the header in every single request.
* If you really want to replicate the behavior of a real Wii U you probably want to change fields like the user agent as well.
* The `FLAG_HAS_SIZE` flag is indeed set in all Wii U games I analyzed, but when I captured packets that were sent to the friend server I noticed that it was *not* set. I think it depends on the PRUDP version that's used, so unless I'm mistaken your patch is just another (maybe better) way of doing it 'wrong'.

I would be willing to add your changes to the master branch but I want to make sure that they don't break any of the example scripts first (it's easy to mess things up with prudp). I'm on vacation right now however, so I can't exactly tell you how soon that will be.

**Comment by mrexodia** [comment]
Thanks for the comments!

- With regards to `Accept-Language`, I guess in `set_device` it can be set based on the `country` to lowercase?
- I will specify the `X-Nintendo-Device-Cert` as an optional parameter to `login` instead then!
- Right now I'm going off what CEMU is doing, to keep my WiiU completely unmodded but I will check if the `User-Agent` is set and add it to the wiki
- My captures are all for Super Mario Maker and whatever friends server that uses, the size is still somewhat inconsistent so I will try to replicate exactly what I see on the wire and just make it possible to specify in the `.cfg`

**Comment by Kinnay** [comment]
Actually, the language is independent from the country. In my case, the country code is "NL" because I live in the Netherlands, but the `Accept-Language` header is still "de" because I set the system language to German. I'd probably keep English the default (like you did), and let the user change it with a generic `set_header` method if he wants to send a different language code to the server.

I think the device certificate should stay in `set_device`, because there are some other requests where it's sent to the server as well (although `login` and `refresh_login` are the only ones I've implemented so far). I'd probably store it in a separate variable in `AccountAPI` and add it to the `Request` object in each method that 'needs' it.

If there is a consistent way to replicate the real behavior I wouldn't add another config setting. I think it depends on the prudp version and whether `FLAG_RELIABLE` is set, so if you can figure out exactly when and why these flags are set that would be very helpful.

**Comment by mrexodia** [comment]
I touched up my commits. Now `Accept-Language` is set to `en` per default and introduced the `set_header` method as you suggested.

I also added a `device_cert` member and set it for the `login` and `refresh_login` headers only if present.

**Comment by Kinnay** [comment]
Looks good.

I just tested it myself, and the `FLAG_HAS_SIZE` change didn't break the friends client or another example script. I'm adding it to master.

**Pull request merged**
