### PR TITLE
WIP: Switch 19.0.0 Support

### PR DESCRIPTION
**Pull request by Ixaruz**
I wanted to look into what changed in the Switch's firmware version 19.0.0 so far.
However, this update will require more than just updating a few strings for User-Agents and stuff.

I'm leaving my current edits in this pull request, until someone is smart enough to figure this out.

Some findings:
- **aauth** got a a bumped API version (v5 to be exact). The only noticable difference i found so far, is that ``media_type`` is now called ``auth_type`` in the request form for ``application_auth_token``. The code has been adapted to reflect those changes. I don't know if the ``challenge`` method needs to be adapted in some way, as I couldn't test that yet.
- requesting an application access token from **baas** requires a ``penneId`` (which I assume are related to the new ``val.hac.lp1.penne.srv.nintendo.net`` and ``god.hac.lp1.penne.srv.nintendo.net`` servers?). I couldn't MITM the requests between my switch and those penne servers, so I don't know anything about this yet
- **dauth** now uses ``key_generation`` 19 (how did we skip 18?)

If this pull request is unappreciated, you can delete/close it if you want!

### CODE REVIEW

**Comment by relm** [comment]
Yeah, I also noticed aauth changed so I held off doing a pull request, as I am less familiar with that portion of the API. 

In addition to the `auth_type` parameter change, looking in account sysmodule I see there's a `challenge` and `challenge_src` parameter referenced. I haven't done a MITM on any of the aauth requests yet and this is just inspecting one of the firmware modules so not sure if that is actually used but worth noting. In v4 these parameters weren't present at all from what I can see.

Relevant string export from the account module:
`https://aauth-%.ndas.srv.nintendo.net/v5/application_auth_tokenapplication_id=%016llx&application_version=%08x&device_auth_token=%.*s&auth_type=NO_CERTapplication_id=%016llx&application_version=%08x&device_auth_token=%.*s&auth_type=DIGITAL&cert=%.*sapplication_id=%016llx&application_version=%08x&device_auth_token=%.*s&auth_type=GAMECARD&gvt=%.*s&cert=%.*s&challenge=%.*s&challenge_src=%.*s@carddevice_auth_token=%.*shttps://aauth-%.ndas.srv.nintendo.net/v5/challenge`

**Comment by Coxxs** [comment]
Penne servers require the client to support TLSv1.3.

If you are using Charles, you can patch this file to make it support TLSv1.3: `charles.jar -> com/xk72/proxy/ssl/SSLSocketConfigurationGenerator.class`.

**Comment by kinnay** [comment]
Thank you for working on this. We skipped key generation 18 because Nintendo forgot to update the dauth client in the 18.0.0. I can also confirm that the challenge and challenge_src parameters were added to gamecard authentication.

I also noticed that a naCountry parameter was added to baas in 18.0.0. We probably want to add that to the baas client as well. The penneId parameter seems to be optional, but it would still be good to figure out where it comes from, and what causes it to be sent.

This will require a bit more reverse engineering work.

**Comment by kinnay** [comment]
I updated the master branch. If anyone wants to figure out how Penne works, help with that would be more than welcome. I also found a new acd_index parameter that is used in friend presence related requests. I haven't figured out its purpose yet, but I added it as a parameter to the code.

Other than that, 19.0.0 support should be ready. I hope I didn't miss anything, because it's becoming a bit hard to keep track of all the changes that Nintendo makes.

**Comment by kinnay** [comment]
Looks like the penne id comes from here: https://switchbrew.org/wiki/NPNS_services#GetJid

**Comment by relm** [comment]
I haven't went through all my traffic logs yet, but I did an MITM on a Switch freshly updated to a 19.0.0 and here's how to obtain the penne ID and password.

All penne requests appear to be sent as HTTP2, in contrast to dauth and most other endpoints that still use HTTP/1.1. 

First, it gets a device token from dauth with client ID `e58171fe439390ce`
```
POST https://dauth-lp1.ndas.srv.nintendo.net/v7/device_auth_token
Accept: */*
Content-Type: application/x-www-form-urlencoded
X-Nintendo-PowerState: FA
Content-Length: 211
```

Payload:
`challenge=x&client_id=e58171fe439390ce&ist=false&key_generation=19&system_version=CusHY#00130000#x2jf5al2EkqJmdvmnTFaL6s4ic7X68N0dY9jnwwcL98=&mac=x`

The resulting token is sent to:
```
POST https://god.hac.lp1.penne.srv.nintendo.net/v1/penne_ids
accept: */*
content-type: application/json
authorization: Bearer DEVICE_TOKEN
```

No request body.

Returns:
`{"id":"<omitted>","password":"<omitted>"}`

Third request:
```
POST https://god.hac.lp1.penne.srv.nintendo.net/v1/immigrate
accept: */*
content-type: application/json
authorization: Bearer DEVICE_TOKEN
content-length: 209
```

JSON payload:
`{"penne_id":"<omitted>","penne_password":"<omitted>","jid":"ID_REMOVED@app-a05.lp1.npns.srv.nintendo.net","jid_password":"<omitted>"}`

From what I can see, the above is not requested after a subsquent reboot (aside from obtaining the dauth token). So I'd imagine the penneId at minimum is saved on the NAND somewhere. The third request looks like it is establishing a relationship with the jid? I don't know where the jid and jid password comes from, maybe that is relevant to what kinnay linked above.

I also noticed the penneId is *always* is sent to BAAS when the Switch requests an application token on initial boot. 

Hopefully this helps.

**Comment by kinnay** [comment]
19.0.1 is now out too. Should be an easy upgrade since not much has changed. I'll probably try to finish 19.0.0+ support some time in the following weeks, but am currently quiet busy.

**Comment by kinnay** [comment]
I added the penne id parameter to the example scripts and released a new version. I hope that this is good.

**Pull request closed without merging**
