### PR TITLE
Update aauth.py to add gamecard support

### PR DESCRIPTION
**Pull request by EpicUsername12**
This PR aims to add gamecard support to NintendoClients.

I made a tool that asks the console to complete the challenge, and allow the python script to pass AAuth authentication.

The repo is here: https://github.com/EpicUsername12/nx-netauth-link

Example usage here: https://github.com/EpicUsername12/nx-netauth-link/blob/master/python/example_mk8dx_get_top_competitions.py

It works well and reliably, with a very decent amount of checks.

I have tested against pre-defined values and seeds from AAuth, and they all matched what the console normally returns.

### CODE REVIEW

**Comment by EpicUsername12** [comment]
If you agree with adding this to Nintendo clients, i will commit the gamecard example

**Comment by kinnay** [comment]
Looks good. I don't think I want to add the example script, because the purpose of NintendoClients is to do this stuff **without** a Switch. I could add a link to your repo to the readthedocs documentation though? If we do add an example script, I think it would be best if it focuses on the gamecard only, without MK8DX stuff around it. What do you think?

**Comment by EpicUsername12** [comment]
It will be whatever you decide, it's your software after all; 

If you want to add an example script, what would it contain? Code up to the NEX login? Or code up to the AAuth token ?

I'm fine with any

**Comment by kinnay** [comment]
I added a link to your repo to the documentation.

**Pull request merged**
