### PR TITLE
DateTime class: add method to convert to a standard datetime

### PR DESCRIPTION
**Pull request by iomintz**
I wanted this so I could use other methods like isoformat().

Question: should the resulting datetime object have its tzinfo set to UTC?

### CODE REVIEW

**Comment by Kinnay** [comment]
I want to accept this. Minor nitpicks:

* I like to keep function names as short as possible. Maybe rename `to_standard_datetime` to `standard_datetime`? The other functions (such as `timestamp()`) are also not prefixed with `to` or `get` for that reason.
* There's an unnecessary `,` behind `self.second()`

Let me know if you disagree.

> Question: should the resulting datetime object have its tzinfo set to UTC?

Yeah I think DateTime objects are always UTC.

**Comment by iomintz** [comment]
> There's an unnecessary , behind self.second()
I always add those because it makes diffs easier. If you need to add another line below it, the diff only adds one line, instead of adding one line and changing another.

**Comment by Kinnay** [comment]
> I always add those because it makes diffs easier. If you need to add another line below it, the diff only adds one line, instead of adding one line and changing another.

Ok that's fine. I mostly commented on it because it's not consistent with the rest of the code :)

Two more things:
* You forgot to rename the `to_standard_datetime` call in the `timestamp()` function
* Why are you calling `replace` on the `datetime` object instead of passing the timezone to the `datetime` constructor directly?

**Comment by iomintz** [comment]
>     * Why are you calling `replace` on the `datetime` object instead of passing the timezone to the `datetime` constructor directly?

In my testing, passing the timezone to the constructor actually converted the timestamp from a local time to UTC. Replace assumes that the timestamp is already in UTC.

**Comment by Kinnay** [comment]
Are you sure? I don't see a difference:

image

Even though my local time zone is not UTC:

image

**Pull request merged**
