### PR TITLE
Add a Pipfile with required dependencies

### PR DESCRIPTION
**Pull request by azillion**

### CODE REVIEW

**Comment by Kinnay** [comment]
Hi,

I'm unfamiliar with pipfiles. They're a way to install all required packages with pip at once right?

I have two questions:
1. NintendoClients supports any python version >= 3.6 at the moment, but your pipfile requires python 3.8. Is there a reason for that? I don't want to raise the required python version unless I need some feature that only exists in a higher version.
2. Why is pylint in there? It's in no way a requirement of NintendoClients. I see it's under the dev-packages section, but in my opinion everyone should decide which packages they need during development themselves.

**Comment by azillion** [comment]
Hi,

They are, but as far as I know they require [pipenv](https://github.com/pypa/pipenv) right now to be used. So I also added a requirements.txt file.

1) I removed the Pipfile.lock and updated the Pipfile so that multiple python versions can be used. Unfortunately there's no way to specify python >= 3.6 in the pipfile, so I just removed the requirements entirely. 
2) Sorry about that! That was left over from my own work, I've removed that from the dependencies.

**Comment by Kinnay** [comment]
Ok I've been reading a bit. Apparently pipfiles and requirements.txt are only intended for applications, not for libraries. The difference is that the requirements of libraries should be flexible, whereas applications are often deployed into a specific environment. That also seems to be the reason that you can only specify a specific python version in pipfiles, instead of a range of python versions. See https://pipenv-fork.readthedocs.io/en/latest/advanced.html#pipfile-vs-setuppy.

NintendoClients is definitely a library and I also want to support as many python versions as possible, so I don't think a pipfile or requirements.txt is the right way to go here. Instead, the correct approach would be to specify the requirements in setup.py with `install_requires`. If you run `pip install .` you'll automatically install the nintendo package and its requirements.

What's your opinion on this?

**Comment by azillion** [comment]
Oh good to know! And sorry about that, I should have researched more.

The setup.py with install_requires does sound like the way to go. Mind if I make a new PR for it?

**Comment by Kinnay** [comment]
Sure, go for it 😉

**Pull request closed without merging**
